# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: dsrcode

builds:
  - id: dsrcode
    main: .
    binary: dsrcode
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - PRIVACY.md
      - TERMS.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

changelog:
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Documentation
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Other
      order: 999
  filters:
    exclude:
      - '^test:'
      - '^ci:'
      - '^chore:'

release:
  github:
    owner: StrainReviews
    name: dsrcode
  prerelease: auto
  make_latest: true
